export const SECTORS: Record<string, string> = {
  ACI:   'Turizam i usluge',
  ADPL:  'Industrija',
  ADRS:  'Turizam i usluge',
  ADRS2: 'Turizam i usluge',
  ARNT:  'Turizam i usluge',
  ATGR:  'Prehrambena industrija',
  AUHR:  'Maloprodaja',
  CKML:  'Prehrambena industrija',
  CROS:  'Osiguranje',
  CROS2: 'Osiguranje',
  CTKS:  'Industrija',
  DDJH:  'Industrija',
  DLKV:  'Industrija',
  ERNT:  'IT i telekomunikacije',
  GRNL:  'Agroprerada',
  HPB:   'Bankarstvo',
  HT:    'Telekomunikacije',
  IG:    'Građevinarstvo',
  IGH:   'Građevinarstvo',
  IKBA:  'Bankarstvo',
  INA:   'Energetika',
  INGR:  'Građevinarstvo',
  JDGT:  'Prijevoz',
  JDPL:  'Prijevoz',
  KODT:  'Elektrotehnika',
  KODT2: 'Elektrotehnika',
  KOEI:  'Elektrotehnika',
  KRAS:  'Prehrambena industrija',
  LKPC:  'Infrastruktura',
  LKRI:  'Infrastruktura',
  MDKA:  'Maloprodaja',
  PLAG:  'Turizam i usluge',
  PODR:  'Prehrambena industrija',
  RIVP:  'Turizam i usluge',
  SNBA:  'Bankarstvo',
  SPAN:  'IT i telekomunikacije',
  TOK:   'Maloprodaja',
  ULPL:  'Prijevoz',
  VLEN:  'Industrija',
  ZABA:  'Bankarstvo',
  ZITO:  'Agroprerada',
};
